# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'personal_subscription'
    action: Create Or Update Resource Group
    resourceGroupName: 'rgvm'
    csmFileLink: 'https://raw.githubusercontent.com/Asmenys/azure-vm/main/vm_template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/Asmenys/azure-vm/main/vm_template-params.json'
    deploymentMode: 'Incremental'
